##
## -------------------------
## |   M E D I A B O X     |
## -------------------------
##
##
## Configuration variables for this file are taken from the .env file
##
## Have docker-compose.yml and .env in the same directory to launch the stack

version: '3.5'

services:

  # ----------------------------------------
  # DELUGEVPN
  # ----------------------------------------
  arch-delugevpn:
    image: binhex/arch-delugevpn
    container_name: delugevpn
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8112:8112'
        - '${IP_ADDRESS}:8118:8118'
        - '${IP_ADDRESS}:58846:58846'
        - '${IP_ADDRESS}:58946:58946'
    cap_add:
        - NET_ADMIN
    environment:
        - VPN_ENABLED=yes
        - VPN_USER=${PIAUNAME}
        - VPN_PASS=${PIAPASS}
        - VPN_REMOTE=${VPN_REMOTE}
        - VPN_PORT=1198
        - VPN_PROTOCOL=udp
        - VPN_DEVICE_TYPE=tun
        - VPN_PROV=pia
        - STRONG_CERTS=no
        - ENABLE_PRIVOXY=yes
        - STRICT_PORT_FORWARD=yes
        - LAN_NETWORK=${CIDR_ADDRESS}
        - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
        - DEBUG=false
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - '${DLDIR}:/data'
        - './delugevpn/config:/config'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # JACKETT
  # ----------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:9117:9117'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './jackett:/config'
        - '${DLDIR}/completed:/downloads'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # JELLYFIN
  # ----------------------------------------
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    network_mode: "bridge"
    user: "${PUID}:${PGID}"
    ports:
        - '${IP_ADDRESS}:8096:8096'
    volumes:
        - './jellyfin:/config'
        - '${MISCDIR}:/media/misc'
        - '${MOVIEDIR}:/media/movies'
        - '${MUSICDIR}:/media/music'
        - '${TVDIR}:/media/tv'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # LIDARR
  # ----------------------------------------
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8686:8686'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './lidarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${MUSICDIR}:/music'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # NZBGet
  # ----------------------------------------
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: 'bridge'
    ports:
      - '${IP_ADDRESS}:6789:6789'
    volumes:
      - './nzbget:/config'
      - '${DLDIR}:/downloads'

  # ----------------------------------------
  # NZBHydra2
  # ----------------------------------------
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    network_mode: 'bridge'
    ports:
      - '${IP_ADDRESS}:5076:5076'
    volumes:
      - './nzbhydra2:/config'
      - '${DLDIR}:/downloads'

  # ----------------------------------------
  # OVERSEERR
  # ----------------------------------------
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    restart: unless-stopped
    network_mode: "bridge"
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - LOG_LEVEL=info
        - TZ=${TZ}
    ports:
        - ${IP_ADDRESS}:5055:5055
    volumes:
        - ./overseerr:/config

  # ----------------------------------------
  # PLEX
  # ----------------------------------------
  plex:
    container_name: plex
    image: plexinc/pms-docker:${PMSTAG}
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:32400:32400/tcp'
        - '${IP_ADDRESS}:3005:3005/tcp'
        - '${IP_ADDRESS}:8324:8324/tcp'
        - '${IP_ADDRESS}:32469:32469/tcp'
        - '${IP_ADDRESS}:1900:1900/udp'
        - '${IP_ADDRESS}:32410:32410/udp'
        - '${IP_ADDRESS}:32412:32412/udp'
        - '${IP_ADDRESS}:32413:32413/udp'
        - '${IP_ADDRESS}:32414:32414/udp'
    environment:
        - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
        - ALLOWED_NETWORKS=${CIDR_ADDRESS}
        - PLEX_UID=${PUID}
        - PLEX_GID=${PGID}
    hostname: ${HOSTNAME}
    volumes:
        - './plex:/config'
        - './plex/transcode:/transcode'
        - '${MISCDIR}:/data/misc'
        - '${MOVIEDIR}:/data/movies'
        - '${MUSICDIR}:/data/music'
        - '${TVDIR}:/data/tvshows'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # PORTAINER
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8000:8000'
        - '${IP_ADDRESS}:9443:9443'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './portainer:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/localtime:/etc/localtime:ro'
    command: -H unix:///var/run/docker.sock

  # ----------------------------------------
  # PROWLARR
  # ----------------------------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - '${IP_ADDRESS}:9696:9696'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - './prowlarr:/config'

  # ----------------------------------------
  # RADARR
  # ----------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:7878:7878'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './radarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${MOVIEDIR}:/movies'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # SONARR
  # ----------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8989:8989'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - './sonarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${TVDIR}:/tv'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # TDARR
  # ----------------------------------------
  tdarr:
    image: haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8265:8265'
        - '${IP_ADDRESS}:8266:8266'
        - '${IP_ADDRESS}:8267:8267'
    environment:
        - TZ=${TZ}
        - PUID=${PUID}
        - PGID=${PGID}
        - UMASK_SET=002
        - serverIP=${IP_ADDRESS}
        - serverPort=8266
        - webUIPort=8265
    volumes:
        - './tdarr/server:/app/server'
        - './tdarr/configs:/app/configs'
        - './tdarr/logs:/app/logs'
        - './tdarr/transcode_cache:/temp'
        - '${MISCDIR}:/data/misc'
        - '${MOVIEDIR}:/data/movies'
        - '${MUSICDIR}:/data/music'
        - '${TVDIR}:/data/tvshows'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # TDARR-NODE
  # ----------------------------------------
  tdarr-node:
    image: haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
        - TZ=${TZ}
        - PUID=${PUID}
        - PGID=${PGID}
        - UMASK_SET=002
        - nodeID=Node_01
        - nodeIP=${IP_ADDRESS}
        - nodePort=8267
        - serverIP=${IP_ADDRESS}
        - serverPort=8266
    volumes:
        - './tdarr/configs:/app/configs'
        - './tdarr/logs:/app/logs'
        - './tdarr/transcode_cache:/temp'
        - '${MISCDIR}:/data/misc'
        - '${MOVIEDIR}:/data/movies'
        - '${MUSICDIR}:/data/music'
        - '${TVDIR}:/data/tvshows'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # TAUTULLI
  # ----------------------------------------
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8181:8181'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - './tautulli:/config'
        - './plex/Library/Application Support/Plex Media Server/Logs:/logs:ro'
    depends_on:
        - plex

  # ----------------------------------------
  # WATCHTOWER
  # ----------------------------------------
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: "bridge"
    hostname: '${HOSTNAME}'
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_SCHEDULE=0 0 */4 * * *
        - WATCHTOWER_INCLUDE_STOPPED=true
        - TZ=${TZ}
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'

